services:
  postgres:
    image: postgres:17
    container_name: kasse-postgres
    environment:
      POSTGRES_USER: kasse_user
      POSTGRES_PASSWORD: kasse_password
      POSTGRES_DB: kasse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
